services:
  redis:
    image: redis

  irods-catalog:
    build:
      context: irods_catalog
    environment:
      - POSTGRES_PASSWORD=testpassword

  irods-catalog-provider:
    build:
      context: irods_catalog_provider
    volumes:
      - shared_volume:/data/ufs
    depends_on:
      - irods-catalog

  ingest-test:
    build:
      context: test
    environment:
      - "PIP_PACKAGE"
      - "TEST_CASE"
      - "IRODS_PORT"
      - "IRODS_HOST"
      - "IRODS_USER_NAME"
      - "IRODS_ZONE_NAME"
      - "IRODS_ENVIRONMENT_FILE"
      - "IRODS_PASSWORD"
    volumes:
      - shared_volume:/data/ufs
    depends_on:
      - redis
      - irods-catalog-provider
      - minio

  minio:
    image: minio/minio:RELEASE.2024-09-13T20-26-02Z
    ports:
      - "19000:19000" # This is the port to use for issuing S3 requests.
      - "19001:19001" # Change this port, if needed, to access the MinIO console webpage.
    command: minio server /data/minio-s3
    environment:
      MINIO_ROOT_USER: irods
      MINIO_ROOT_PASSWORD: irodsadmin
      MINIO_ADDRESS: ":19000"
      MINIO_CONSOLE_ADDRESS: ":19001"

volumes:
    shared_volume:
