name: run-tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │  ┌───────────── day of the month (1 - 31)
    #        │  │  │  ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │  │  │  ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │  │  │  │
    #        *  *  *  *  *
    - cron: "0  7  *  *  1" # Run at 7:00am UTC every Monday morning.

jobs:
  run_tests:
    name: "Run Tests - Python ${{ matrix.python_version }}"
    strategy:
      matrix:
        python_version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Build Docker Images
        run: |
          compose_file=docker-compose.yml
          cd docker/ingest-test
          docker compose -f ${compose_file} build --build-arg 'python_version=${{ matrix.python_version }}'

      - name: Run ingest tests
        run: |
          compose_file=docker-compose.yml
          cd docker/ingest-test
          docker compose -f ${compose_file} --env-file icommands.env up --abort-on-container-exit

      - name: Stop Docker Compose services
        if: always()
        run: |
          compose_file=docker-compose.yml
          cd docker/ingest-test
          docker compose -f ${compose_file} down
